FROM docker.io/nginx:alpine
RUN rm -rf /usr/share/nginx/html
RUN mkdir -p /var/www/html/web
RUN sed -i 's#/usr/share/nginx/html#/var/www/html#g' /etc/nginx/conf.d/default.conf
COPY build/web /var/www/html/web
COPY build/web/index.html /var/www/html/
COPY config.sample.json /var/www/html/web/config.json
